# Generated by Django 5.1.1 on 2024-09-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.category'),
        ),
    ]
