# Generated by Django 5.1.1 on 2024-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
