# Generated by Django 5.1.1 on 2024-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_category_options_category_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ManyToManyField(to='students.category'),
        ),
    ]
