# Generated by Django 5.1.1 on 2024-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_teacher_alter_student_options_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], default='N', max_length=1),
        ),
    ]
