# Generated by Django 5.1.1 on 2024-09-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_category_options_alter_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_date'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
