# Generated by Django 5.1.1 on 2024-09-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
    ]
