# Generated by Django 5.1.1 on 2024-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='file/products/')),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('bigint_field', models.BigIntegerField(blank=True, null=True)),
                ('json_field', models.JSONField(blank=True, null=True)),
                ('ip_field', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
